[m0]
	model_name='ResNet152'
	augment_multiplication=10

	batch_size=2048
	num_unique_classes=27795
	learning_rate=0.00005
	beta_1=0.9
	beta_2=0.999
	label_smoothing=0.05
	stopping_threshold=98

	img_height=437
	img_width=313

	deckdrafterprod_img_keys=['card_images', 'image_url']

	is_final=true


